### PR TITLE
Fixed null pointer exception in getValidSelector method

### PR DESCRIPTION
**Pull request by Kricheldorf**
Fix for #7.

I added a condition to check if the selectorText matcher the regex and to check if the matches array has the required.

If you think the code needs improvements, feel free to comment here. I'd love to hear feedback. @thebrubaker

### CODE REVIEW

**Comment by robertfausk** [comment]
Any updates on this?

**Comment by thebrubaker** [comment]
I like it, I'll re-review in the morning and pull it in

**Comment by robertfausk** [comment]
LGTM. Just tried it and I got same error like @Kricheldorf without this PR.

**Comment by Kricheldorf** [comment]
Do you think its ready for merging? I am using the version on my fork in my projects, but I'd like to use the official version with the patch.

**Comment by robertfausk** [comment]
Same here! Looking forward to get this merged very soon.
@thebrubaker vue-element-queries is great!

**Comment by Kricheldorf** [comment]
Any updates on this?

**Comment by Kricheldorf** [comment]
Closing this issue for now since it seems the project is dead. The fix is still valid, feel free to apply it if you continue to work on this.

**Pull request closed without merging**
