### PR TITLE
Fix bug to prevent Chrome 64 ..

### PR DESCRIPTION
**Pull request by Mattchewone**
throwing errors about crawling external stylesheets

### CODE REVIEW

**Comment by thebrubaker** [comment]
Thanks for submitting this, I have to figure out how to rebuild the package with the new vue cli tools, which might be a little bit, then I can review + merge this in.

**Comment by Mattchewone** [comment]
Yer I am not too familiar with bundling a Vue plugin, if I get a chance to look into it I will gladly offer some help.

**Comment by thebrubaker** [comment]
Ok I just pushed the new build process, so this may need to be resubmitted. Also I'm on the latest chrome 66 and don't see any errors immediately. I might need to do more testing.

**Comment by thebrubaker** [comment]
I also updated the ResizeSensor from css-element-queries which may have fixed it. Can you check v0.3.0?

**Comment by Mattchewone** [comment]
I was getting lots of these errors earlier https://stackoverflow.com/questions/48753691/cannot-access-cssrules-from-local-css-file-in-chrome-64/49160760#49160760

Wrapping the crawler in the `try/catch` solved the issue, so I assumed that was the issue. Maybe it wasn't.

I will try tomorrow for sure! Thanks very much!!

**Comment by thebrubaker** [comment]
Aha! When accessing the css file from a local filesystem, it now properly violates CORs and thats why it wouldn't work. They recommend using a local development server: https://developer.mozilla.org/en-US/docs/Learn/Common_questions/set_up_a_local_testing_server#Running_a_simple_local_HTTP_server

**Comment by Mattchewone** [comment]
Is it possible to put in the fix that I have in the PR, so that there won't be a need to run another process so that you can run the app in dev mode? 
Currently working on a Nuxt project, and that would mean I would have setup a separate process and loose all the hot reload functionality by having to build it and have it served by another process.

**Comment by Mattchewone** [comment]
Also is it possible for you to include the build steps?

**Comment by thebrubaker** [comment]
If you would like to fork, install the new vue-cli and run `vue build ./src -t lib`

**Comment by thebrubaker** [comment]
I'm probably not going to merge this in due to it catching an exception only to silence that there is an error, rather than letting the developer know something is wrong. The PR would need to address the root cause of whats happening, and I can try to look a little further into it.

**Comment by Mattchewone** [comment]
Sure. 

So looking into it a little more, we only want to crawl local stylesheets. The issue seems to be when crawling an external one. For example I have some google material styles being pulled in, once they are accessed it throws.

Maybe we could check for non-external stylesheets, not sure how hardy this is:
```js
ifValidRules(stylesheet, callback) {
    if (stylesheet.href === null && stylesheet.cssRules) {
      callback(stylesheet.cssRules);
    }
  }
```

**Comment by thebrubaker** [comment]
@Mattchewone ah yes that would make sense! I'll look into how we can determine a local stylesheet including what you have above. It's all about the domain it's being loaded from, so we'll have to figure out how to do that check.

**Comment by thebrubaker** [comment]
Also you might need to pull the most recent commit into this PR to squash the conflicts.

**Comment by Mattchewone** [comment]
I was going to use my forked version for now until there is a resolved solution to this problem. 

Feel free to close this PR for now, unless you think it is of use?

**Pull request closed without merging**
